import type { Course } from "./types";

// Hardcoded list of the best free YouTube courses and paid certifications for GenAI/ML
// Since Coursera and Udemy don't have free public APIs, we maintain a curated list.
export const CURATED_COURSES: Course[] = [
  // ── FREE YOUTUBE COURSES ──────────────────────────────────────────────
  {
    id: "yt-karpathy-nn",
    title: "Neural Networks: Zero to Hero",
    creator: "Andrej Karpathy",
    platform: "YouTube",
    type: "free",
    url: "https://www.youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ",
    description: "Build neural networks from scratch in code. Covers backprop, GPT, tokenization.",
  },
  {
    id: "yt-3b1b-nn",
    title: "Neural Networks (Deep Learning)",
    creator: "3Blue1Brown",
    platform: "YouTube",
    type: "free",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi",
    description: "Beautiful visual explanations of how neural networks learn.",
  },
  {
    id: "yt-stanford-cs229",
    title: "CS229: Machine Learning (Stanford)",
    creator: "Stanford Online",
    platform: "YouTube",
    type: "free",
    url: "https://www.youtube.com/watch?v=jGwO_UgTS7I&list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU",
    description: "Andrew Ng's legendary Stanford ML course — full lectures.",
  },
  {
    id: "yt-stanford-cs231n",
    title: "CS231n: CNNs for Visual Recognition",
    creator: "Stanford Online",
    platform: "YouTube",
    type: "free",
    url: "https://www.youtube.com/watch?v=vT1JzLTH4G4&list=PL3FW7Lu3i5JvHM8ljYj-zLfQRF3EO8sYv",
    description: "Deep dive into convolutional neural networks for computer vision.",
  },
  {
    id: "yt-mit-intro-dl",
    title: "MIT 6.S191: Introduction to Deep Learning",
    creator: "MIT",
    platform: "YouTube",
    type: "free",
    url: "https://www.youtube.com/playlist?list=PLtBw6njQRU-rwp5__7C0oIVt26ZgjG9NI",
    description: "MIT's intro course on deep learning foundations and applications.",
  },
  {
    id: "yt-huggingface-nlp",
    title: "NLP Course",
    creator: "Hugging Face",
    platform: "YouTube",
    type: "free",
    url: "https://www.youtube.com/playlist?list=PLo2EIpI_JMQvWfQndUesu0nPBAtZ9gP1o",
    description: "Learn NLP with Transformers, tokenizers, and the Hugging Face ecosystem.",
  },
  {
    id: "yt-sentdex-pytorch",
    title: "PyTorch Deep Learning & ML",
    creator: "sentdex",
    platform: "YouTube",
    type: "free",
    url: "https://www.youtube.com/playlist?list=PLQVvvaa0QuDdeMyHEYc0gxFpYwHY2Qfdh",
    description: "Hands-on PyTorch tutorials from data loading to training neural networks.",
  },
  {
    id: "yt-statquest-ml",
    title: "Machine Learning Fundamentals",
    creator: "StatQuest (Josh Starmer)",
    platform: "YouTube",
    type: "free",
    url: "https://www.youtube.com/playlist?list=PLblh5JKOoLUICTaGLRoHQDuF_7q2GfuJF",
    description: "Clear, fun explanations of ML algorithms like Random Forest, XGBoost, and more.",
  },

  // ── PAID CERTIFICATIONS ────────────────────────────────────────────────
  {
    id: "coursera-dlai-mls",
    title: "Machine Learning Specialization",
    creator: "Andrew Ng (DeepLearning.AI)",
    platform: "Coursera",
    type: "paid",
    url: "https://www.coursera.org/specializations/machine-learning-introduction",
    description: "The #1 ML course on the planet. Covers supervised, unsupervised learning & recommenders.",
  },
  {
    id: "coursera-dlai-dls",
    title: "Deep Learning Specialization",
    creator: "Andrew Ng (DeepLearning.AI)",
    platform: "Coursera",
    type: "paid",
    url: "https://www.coursera.org/specializations/deep-learning",
    description: "5-course series covering CNNs, RNNs, LSTM, Transformers, and optimization.",
  },
  {
    id: "coursera-dlai-genai",
    title: "Generative AI with LLMs",
    creator: "DeepLearning.AI + AWS",
    platform: "Coursera",
    type: "paid",
    url: "https://www.coursera.org/learn/generative-ai-with-llms",
    description: "Fine-tuning, RLHF, prompt engineering, and deploying LLMs at scale.",
  },
  {
    id: "coursera-google-ml",
    title: "Google Machine Learning Crash Course",
    creator: "Google",
    platform: "Coursera",
    type: "paid",
    url: "https://www.coursera.org/professional-certificates/google-advanced-data-analytics",
    description: "Google's professional certificate for advanced data analytics and ML.",
  },
  {
    id: "udemy-pytorch-dl",
    title: "PyTorch for Deep Learning & ML",
    creator: "Daniel Bourke",
    platform: "Udemy",
    type: "paid",
    url: "https://www.udemy.com/course/pytorch-for-deep-learning/",
    description: "Comprehensive PyTorch bootcamp from zero to mastery.",
  },
  {
    id: "udemy-ml-az",
    title: "Machine Learning A-Z",
    creator: "Kirill Eremenko & Hadelin de Ponteves",
    platform: "Udemy",
    type: "paid",
    url: "https://www.udemy.com/course/machinelearning/",
    description: "Hands-on ML with Python & R. Covers regression, classification, clustering.",
  },
  {
    id: "dlai-langchain",
    title: "LangChain for LLM App Development",
    creator: "DeepLearning.AI",
    platform: "DeepLearning.AI",
    type: "paid",
    url: "https://learn.deeplearning.ai/courses/langchain",
    description: "Build LLM-powered apps with chains, memory, agents, and retrieval.",
  },
  {
    id: "dlai-finetuning",
    title: "Finetuning Large Language Models",
    creator: "DeepLearning.AI",
    platform: "DeepLearning.AI",
    type: "paid",
    url: "https://learn.deeplearning.ai/courses/finetuning-large-language-models",
    description: "Learn when and how to fine-tune LLMs vs. prompt engineering.",
  },
];
